let jState=null,jBusy=false,jHistory=[],jResults=[];
const jPanel=document.createElement('div');jPanel.id='t-jev';jPanel.className='hidden';
jPanel.innerHTML=`<style>#t-jev:not(.hidden){display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:18px;align-items:start}#t-jev>.card:last-child{grid-column:1/-1}#t-jev textarea{font-family:inherit}#t-jev label{display:block;margin:12px 0}#t-jev details{padding:12px 0;border-bottom:1px solid var(--line)}#t-jev summary{cursor:pointer;font-weight:600}#t-jev pre{white-space:pre-wrap;overflow-wrap:anywhere}#t-jev .card{min-width:0}@media(max-width:1000px){#t-jev:not(.hidden){grid-template-columns:minmax(0,1fr)}}</style><div class="card"><h2>추가 질문 관리</h2><p>어드민과 89번 이상 앱의 Jev 테스트에서 맥락 질문을 시험할 수 있습니다. 규칙을 앱에 적용하면 다음 요청부터 반영됩니다. 실제 일기 생성에는 연결하지 않습니다.</p><p id="jStatus" class="muted"></p><div id="jEditor"></div><div class="row"><button onclick="jSave()">초안 저장</button><button class="ghost" onclick="loadJev()">저장된 규칙 다시 불러오기</button><button class="pri" onclick="jApply()">규칙 앱에 적용</button></div><p id="jNotice" role="status"></p></div>
<div class="card"><h3>대화 테스트</h3><p>실제 API 비용이 발생합니다. 원문과 답변은 이 화면에서만 유지됩니다. 맥락 질문 생성은 OpenAI, 기존 질문 선택은 TypeSafe로 재료를 전송합니다.</p><label>일기 재료<textarea id="jInput" rows="5" maxlength="12000"></textarea></label><div class="row"><select id="jWhich"><option value="draft">화면의 수정안</option><option value="active">현재 운영 규칙</option></select><button onclick="jTest(false)">질문 받기</button><button class="ghost" onclick="jTest(true)">같은 재료로 두 규칙 비교</button><button class="ghost" onclick="jReset()">새 대화</button></div><div id="jConversation"></div><label>질문에 대한 답변<textarea id="jAnswer" rows="3" maxlength="3000"></textarea></label><button onclick="jContinue()">답변하고 다음 질문 받기</button><p id="jTotal"></p><p class="muted">질문 아래 <b>답변 칩</b>은 Jev 가 재료의 사실에서 뽑은 보기(0~3개)이고, '건너뛰기'·'더 쓸 말 없어요'는 항상 붙는 고정 칩입니다. 칩을 누르면 그 문구가 답변으로 들어가 다음 질문을 바로 요청합니다. 마음·생각을 묻는 질문에는 칩이 없습니다.</p><p class="muted">판단 근거는 짧은 결과 설명이며 내부 사고 과정이 아닙니다. Jev의 확신도는 정확도가 아닙니다. 비용은 모델별 입력·출력 토큰 단가와 1달러=1,400원 기준 추정치입니다.</p></div><div class="card"><h3>적용 이력</h3><div id="jVersions"></div></div>
<div class="card" id="jCasesCard"><h3>테스트 사례·검토 <span class="help" data-h="앱 Jev 테스트와 이 화면의 대화 테스트에서 나온 결정이 쌓입니다. 질문이 있던 사례가 10건 모이면 Gemini 가 질문의 적절성을 검토(적절/수정 제안), 질문이 없던(종료) 사례가 10건 모이면 후속 질문 후보를 만듭니다. 종료가 맞았는지는 Jev 판단을 그대로 둡니다. 결과는 참고 의견이며 규칙에 자동 반영되지 않습니다. '규칙 예시로 복사'는 왼쪽 초안의 공통 규칙 끝에 예시 한 줄을 붙입니다. 사례는 90일 뒤 자동 삭제.">?</span></h3>
<div class="row"><select id="jcKind"><option value="all">전체</option><option value="ask">질문 있음</option><option value="skip">질문 없음(종료)</option></select><label style="display:inline-flex;align-items:center;gap:6px;margin:0"><input id="jcOnly" type="checkbox" checked> 제안 있는 것만</label><button class="ghost" onclick="jcLoad()">새로고침</button><button class="pri" onclick="jcReviewNow()">지금 검토</button><span id="jcPending" class="muted"></span></div>
<div id="jcList"></div></div>`;
document.getElementById('t-diaryprompts').after(jPanel);
async function jGuard(fn){if(jBusy)return;jBusy=true;jPanel.querySelectorAll('button,input,textarea,select').forEach(x=>x.disabled=true);try{await fn();}catch(e){$('jNotice').textContent='실패: '+e.message+' · 자동 재시도하지 않았습니다.';toast(e.message,true);}finally{jBusy=false;jPanel.querySelectorAll('button,input,textarea,select').forEach(x=>x.disabled=false);}}
async function loadJev(){await jGuard(async()=>{jState=await api('jev.get');jRender(jState.draft||jState.active);const h=await api('jev.history');$('jVersions').innerHTML=(h.rows||[]).map(v=>`<p>${esc(fmtT(v.changed_at))} · ${esc(v.new_value?.label||'')} <button class="ghost" onclick="jRestore(${Number(v.id)})">이 버전 복원</button></p>`).join('')||'아직 적용 이력이 없습니다.';});}
function jRender(c){$('jStatus').textContent='운영: '+jState.active.label+' · '+jState.active.id;$('jEditor').innerHTML=`<label>질문 방식<select id="jEngine" onchange="jEngineView()"><option value="contextual" ${c.engine==='contextual'?'selected':''}>입력에 맞춰 질문 작성 · GPT-6 Luna</option><option value="jev" ${c.engine!=='contextual'?'selected':''}>기존 문구에서 선택 · Jev</option></select></label><label>규칙 이름<input id="jLabel" maxlength="120" value="${esc(c.label)}"></label><label>최대 질문 횟수 (1~10)<input id="jMax" type="number" min="1" max="10" value="${c.max_turns}"></label><label>공통 판단 규칙<textarea id="jRules" rows="6" maxlength="6000">${esc(c.instructions)}</textarea></label><div id="jLegacy"><p class="muted">아래 유형은 기존 Jev 선택 방식에만 적용됩니다.</p><div id="jItems">${c.items.map(q=>jItem(q)).join('')}</div><button class="ghost" onclick="jAdd()">질문 유형 추가</button></div>`;$('jNotice').textContent='초안 저장만으로는 운영에 반영되지 않습니다.';jEngineView();}
function jItem(q){return `<details class="jItem"><summary>${esc(q.text)} <small class="muted">${esc(q.key)}</small></summary><label>유형 식별자<input data-k="key" maxlength="40" value="${esc(q.key)}"></label><label>질문 문구<input data-k="text" maxlength="200" value="${esc(q.text)}"></label><label>사용·제외 조건<textarea data-k="criterion" rows="3" maxlength="2000">${esc(q.criterion)}</textarea></label><button class="ghost" onclick="this.closest('details').remove()">유형 삭제</button></details>`;}
function jAdd(){if(document.querySelectorAll('.jItem').length>=20)return toast('최대 20개입니다.',true);$('jItems').insertAdjacentHTML('beforeend',jItem({key:'question_'+Date.now(),text:'',criterion:''}));}
function jRead(){return {engine:$('jEngine').value,id:'preview',label:$('jLabel').value,instructions:$('jRules').value,max_turns:Number($('jMax').value),items:[...document.querySelectorAll('.jItem')].map(el=>Object.fromEntries(['key','text','criterion'].map(k=>[k,el.querySelector(`[data-k="${k}"]`).value])))};}
async function jSave(){await jGuard(async()=>{const r=await api('jev.save',{bundle:jRead(),expected_id:jState.draft?.id??null});jState.draft=r.bundle;$('jNotice').textContent='초안 저장 완료. 운영은 그대로입니다.';});}
async function jApply(){await jGuard(async()=>{if(!jState.draft)throw Error('먼저 초안을 저장해 주세요.');const shown=jRead(),saved={...jState.draft,id:'preview'};if(JSON.stringify(shown)!==JSON.stringify(saved))throw Error('화면의 변경 사항을 먼저 초안으로 저장해 주세요.');const r=await api('jev.apply',{draft_id:jState.draft.id,expected_id:jState.active_id});jState.active=r.bundle;jState.active_id=r.bundle.id;$('jStatus').textContent='운영: '+r.bundle.label+' · '+r.bundle.id;$('jNotice').textContent='적용 완료. 앱의 다음 테스트부터 반영됩니다.';await jVersions();});}
async function jRestore(id){await jGuard(async()=>{const r=await api('jev.restore',{audit_id:id,expected_id:jState.active_id});jState.active=r.bundle;jState.active_id=r.bundle.id;jRender(r.bundle);$('jNotice').textContent='복원 완료';await jVersions();});}
function jReset(){jHistory=[];$('jConversation').textContent='';$('jAnswer').value='';}
async function jTest(compare){await jGuard(async()=>{const text=$('jInput').value.trim();if(!text)throw Error('재료를 입력해 주세요.');const modes=compare?['active','draft']:[$('jWhich').value];jHistory=[];for(const which of modes){const start=performance.now();const r=await api('jev.test',{which,bundle:jRead(),text,turns:0});jShow(r,which,performance.now()-start);if(!compare)jHistory=[{text,result:r,which,base:text,bundle:jRead()}];}});}
function jChips(r){if(r.choice==='skip')return '';const own=(r.options||[]).map(o=>`<button class="ghost jChip" data-a="${esc(o)}">${esc(o)}</button>`).join('');return `<div class="jChips">${own}<button class="ghost jChip jFixed" data-a="(이 질문은 건너뛸게요)">건너뛰기</button><button class="ghost jChip jFixed" data-a="더 쓸 말이 없어요.">더 쓸 말 없어요</button></div>`;}
function jShow(r,which,elapsed){jResults.push(r);const card=document.createElement('div');card.className='card';card.innerHTML=`<b>${which==='active'?'운영':'수정안'} · ${esc(r.question)}</b>${jChips(r)}<p>화면 왕복 ${Math.round(elapsed)}ms · 서버 ${Math.round(r.server_ms)}ms · 모델 왕복 ${Math.round(r.provider_ms)}ms · ${r.cost?Number(r.cost.krw).toFixed(4)+'원':'비용 확인 불가'}</p><p>모델: ${esc(r.model||'—')} · 적용 버전: ${esc(r.version)}</p><details><summary>선택 항목과 판단 기준</summary><p>${esc(r.choice)} · ${esc(r.criterion||r.reason||'')}</p><p>확신도 ${esc(r.confidence??'—')}</p><pre>${esc(JSON.stringify(r.probabilities,null,2))}</pre></details>`;card.querySelectorAll('.jChip').forEach(b=>b.onclick=()=>{$('jAnswer').value=b.dataset.a;jContinue();});$('jConversation').append(card);$('jTotal').textContent='이 화면의 성공 응답 누적 추정 비용: '+jResults.reduce((s,x)=>s+(x.cost?.krw||0),0).toFixed(4)+'원 (실패·사용량 미확인 비용 제외)';}
async function jContinue(){await jGuard(async()=>{const prev=jHistory.at(-1);if(!prev)throw Error('단일 규칙으로 먼저 질문을 받아 주세요.');if(prev.result.choice==='skip')throw Error('질문이 종료됐습니다. 규칙을 수정하고 새 대화를 시험해 주세요.');if($('jInput').value.trim()!==prev.base)throw Error('재료가 변경됐습니다. 질문 받기로 새 대화를 시작해 주세요.');if(JSON.stringify(jRead())!==JSON.stringify(prev.bundle))throw Error('규칙이 변경됐습니다. 질문 받기로 새 대화를 시작해 주세요.');const answer=$('jAnswer').value.trim();if(!answer)throw Error('답변을 입력해 주세요.');const text=prev.text+'\n질문: '+prev.result.question+'\n답변: '+answer;const start=performance.now();const r=await api('jev.test',{which:prev.which,bundle:prev.bundle,expected_id:prev.result.version,text,turns:jHistory.length});jShow(r,prev.which,performance.now()-start);jHistory.push({text,result:r,which:prev.which,base:prev.base,bundle:prev.bundle});$('jAnswer').value='';});}
async function saveAdRetention(){const hours=Number($('adRetentionHours').value);if(!Number.isInteger(hours)||hours<1||hours>8760)return toast('1~8760시간의 정수를 입력해 주세요.',true);const old=Number(pol('ad.telemetry_hours')?.value??48);if(hours<old&&!confirm('보관 기간을 줄이면 다음 삭제 작업에서 기준보다 오래된 원본 로그가 영구 삭제됩니다. '+hours+'시간으로 변경할까요?'))return;try{await api('policies.set',{key:'ad.telemetry_hours',value:hours});await loadPolicies();$('adRetentionState').textContent='저장 완료 · '+hours+'시간 보관 · 매시간 10분 삭제 작업에 반영';toast('보관 기간 저장 완료');}catch(e){toast(e.message,true);}}

async function jVersions(){const h=await api("jev.history");$("jVersions").innerHTML=(h.rows||[]).map(v=>`<p>${esc(fmtT(v.changed_at))} · ${esc(v.new_value?.label||"")} <button class="ghost" onclick="jRestore(${Number(v.id)})">이 버전 복원</button></p>`).join("")||"아직 적용 이력이 없습니다.";}

function jEngineView(){$("jLegacy").classList.toggle("hidden",$("jEngine").value!=="jev");}
// ── 테스트 사례·검토 (2026-10-01)
async function jcLoad(){try{const r=await api('jev.cases',{kind:$('jcKind').value,only_suggest:$('jcOnly').checked});$('jcPending').textContent=`미검토: 질문 있음 ${r.pending.ask}건 · 질문 없음 ${r.pending.skip}건 (10건이 되면 자동 검토)`;
 const v={ok:'적절',revise:'수정 제안',suggest:'후속 질문 후보',none:'검토 없음'};
 $('jcList').innerHTML=(r.rows||[]).map(x=>`<details class="jc"><summary>${esc(fmtT(x.created_at))} · ${x.source==='app'?'앱':'어드민'} · ${x.turns}차 · <b>${x.decision==='ask'?'질문: '+esc(x.question):'질문 없이 진행'}</b>${(x.options||[]).length?` <small class="muted">칩: ${esc(x.options.join(' · '))}</small>`:''}${x.review?` · <span class="tag">${esc(v[x.review.verdict]||x.review.verdict)}</span>`:' · <span class="muted">미검토</span>'}</summary>
 <pre>${esc(x.material)}</pre><p class="muted">Jev 근거: ${esc(x.basis||'—')} · 규칙 ${esc(x.version||'—')}</p>
 ${x.review?`<p><b>${esc(v[x.review.verdict]||'')}</b>${x.review.suggestion?` — <span class="jcSug">${esc(x.review.suggestion)}</span> <button class="ghost" data-sug="${esc(x.review.suggestion)}" data-mat="${esc(x.material.split('\n')[0].slice(0,60))}" onclick="jcAdopt(this)">규칙 예시로 복사</button>`:''}</p><p class="muted">이유: ${esc(x.review.reason||'—')}</p>`:''}</details>`).join('')||'<p class="muted">표시할 사례가 없습니다.</p>';
}catch(e){toast(e.message,true);}}
async function jcReviewNow(){await jGuard(async()=>{const r=await api('jev.review_now');const s=(r.summary||[]).map(x=>`${x.kind==='question_check'?'질문 검토':'후속 질문 후보'} ${x.reviewed}건${x.error?' · 실패: '+x.error:''}`).join(' / ')||'검토할 사례가 없습니다.';toast(s);await jcLoad();});}
function jcAdopt(btn){const t=$('jRules');if(!t)return toast('왼쪽 초안 규칙 칸을 먼저 불러와 주세요.',true);const line=`예: '${btn.dataset.mat}' → '${btn.dataset.sug}'`;t.value=(t.value.trimEnd()+'\n'+line).trim();t.scrollTop=t.scrollHeight;toast('초안 규칙 끝에 예시를 붙였습니다. 초안 저장 → 규칙 앱에 적용 순서로 반영하세요.');}
(()=>{const prior=openTab;openTab=function(name,force){prior(name,force);if(name==='jev')jcLoad();};$('jcKind').onchange=jcLoad;$('jcOnly').onchange=jcLoad;const st=document.createElement('style');st.textContent='#jCasesCard details.jc{padding:8px 0}#jCasesCard .tag{background:#EEE4F4;color:#4B0082;border-radius:99px;padding:1px 8px;font-size:12px}#jCasesCard .jcSug{font-weight:700}#t-jev .jChips{display:flex;flex-wrap:wrap;gap:6px;margin:8px 0}#t-jev .jChip{padding:5px 11px;border-radius:99px;font-size:13px}#t-jev .jFixed{opacity:.75}#jCasesCard pre{max-height:180px;overflow:auto;background:#faf7fc;padding:8px;border-radius:8px;font-size:12.5px}';document.head.append(st);})();

